PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = 0

KENVYRA_BUILD_DATE := $(shell date -u +%Y%m%d)

KENVYRA_BUILD_ZIP_TYPE := VANILLA

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(KENVYRA_BUILDTYPE)),)
    KENVYRA_BUILDTYPE := UNOFFICIAL
endif

ifeq ($(KENVYRA_OFFICIAL), true)
    KENVYRA_BUILDTYPE := OFFICIAL
endif

ifeq ($(KENVYRA_MICROG), true)
    KENVYRA_BUILD_ZIP_TYPE := MICROG
endif

KENVYRA_VERSION_SUFFIX := $(KENVYRA_BUILD)-$(KENVYRA_BUILDTYPE)-$(KENVYRA_BUILD_DATE)-$(KENVYRA_BUILD_ZIP_TYPE)

# Internal version
KENVYRA_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(KENVYRA_VERSION_SUFFIX)

# Display version
KENVYRA_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(KENVYRA_VERSION_SUFFIX)
